// This file is automatically generated for ZappTek
// Do not hardcode keys here — always use Vercel env variables

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// These come from Vercel Environment Variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error("❌ Supabase environment variables are missing.");
}

// Create Supabase client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: localStorage,
  },
  global: {
    headers: {
      "X-Client-Info": "zapptek-web",
    },
  },
});
